### ISSUE TITLE
Suppliers

### ISSUE THREAD

**Issue by smfuller1** [agricure/orderbook#2]
Details needed for suppliers:
Supplier name
Address
Order e mail address
Pricing contact and e mail address
Credit control contact and e mail address
bank account name, sort code, account number.
Have attached screenshot of how it looks at the moment
<img width="845" alt="screen shot 2018-12-03 at 14 53 39" src="https://user-images.githubusercontent.com/45420650/49381376-a503f100-f70b-11e8-9084-24e7248b8b25.png">

**Comment by szolsztor** [comment]
a few questions here:

- [ ] the supplier name and order email address are already in the system, or is this referring to something else?
- [ ] how will the bank details be used within the system? or is it just for recording the details?
- [ ] could you have multiple pricing and credit control contacts?
- [ ] could the same person be a pricing and credit control contact?
- [ ] is the address for the invoice address?

**Comment by smfuller1** [comment]
Supplier name and order e mail addresses - yes they are in the system now - just couldn't see them on the new version.
Bank details print out on the final statement that we generate to the client
More likely to have one pricing and one credit control contact.
No - always different people for pricing and credit control
Do you mean supplier address? yes - the address goes on the client statement for cheques to be sent to

**Comment by szolsztor** [comment]
Is the final statement something that happens yearly (and does it happen on the same day for all clients), and is it a report you want the system to generate?

**Comment by szolsztor** [comment]
Closing this issue and opened smaller ones to track their progress
